FROM {{ namespace }}/ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get install -y --no-install-recommends \
        qemu-utils \
        ipmitool \
        socat \
        openssh-client \
    && apt-get clean

USER ironic
